# Referene: https://dart.dev/effective-dart/documentation

name: records
version: 1.0.0
description: >-
  Hello world
repository: https://github.com/michelou/golang-examples

environment:
  sdk: '>=3.1.0'

dev_dependencies:
  lint: ^2.1.2
