# Referene: https://dart.dev/effective-dart/documentation

name: hello-dart
version: 1.0.0
description: >-
  Hello dart
repository: https://github.com/michelou/dart-examples

environment:
  sdk: '>=3.1.0'

dev_dependencies:
  lint: ^2.1.2
