# Referene: https://dart.dev/effective-dart/documentation

name: macros_example
version: 1.0.0
description: >-
  Macros example
repository: https://github.com/michelou/dart-examples

environment:
  sdk: ^3.5.4

dependencies:
  macros: ^0.1.2-main.4
