# Referene: https://dart.dev/effective-dart/documentation

name: macros_example
version: 1.0.0
description: >-
  Macros example
repository: https://github.com/michelou/dart-examples

environment:
  sdk: ^3.6.1

# https://pub.dev/packages/macros/versions
dependencies:
  macros: ^0.1.3-main.0  # ^0.1.2-main.4
